
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "1",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Chicken Salad",
    RECIPE_ID: "2",
    INGREDIENTS: "Chicken,Salad",
    CALORIES: "378",
    PROTEIN: "47",
    CARBS: "284",
    FAT: "40",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "35",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "3",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "4",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "5",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "6",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "7",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "8",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "9",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
  {
    NAME: "Really Delicious Test Recipe",
    RECIPE_ID: "10",
    INGREDIENTS: "Cabbage, BLT, Porridge,Soy",
    CALORIES: "286",
    PROTEIN: "20",
    CARBS: "160",
    FAT: "15",
    COOKING_DIFFICULTY: "1",
    COOKING_TIME_MINS: "25",
  },
];
