const COLS = {
  C_BG: "#A6E6AB",
  C_RED: "#FB4B3D",
  C_LOGO_BG: "#FFC9D9",
  C_YELLOW: "#FFF4BA",
  C4_DARK_TEXT: "#65676F",
  C5_LIGHT_TEXT: "#C4C4C4",
  C6_WHITE_TEXT: "#FDFFF7"
};

export { COLS };
